# Generated by Django 6.0.4 on 2026-06-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mySettings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('topicId', models.AutoField(primary_key=True, serialize=False)),
                ('topicName', models.CharField(max_length=100)),
                ('topicDescription', models.CharField(max_length=500)),
            ],
        ),
    ]
