# Generated by Django 6.0.4 on 2026-06-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProfile', '0003_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('topicId', models.AutoField(primary_key=True, serialize=False)),
                ('topicName', models.CharField(max_length=100)),
                ('topicDescription', models.CharField(max_length=500)),
            ],
        ),
    ]
