# Generated by Django 6.0.4 on 2026-06-17 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myProfile', '0004_topics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topics',
        ),
    ]
