# Generated by Django 6.0.4 on 2026-08-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myPosts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='imagePost',
        ),
    ]
