# Generated by Django 6.0.4 on 2026-04-22 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='confirm_password',
        ),
    ]
