# Generated by Django 6.0.4 on 2026-04-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_is_admin_newuser_is_superuser_newuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
