# Generated by Django 6.0.4 on 2026-04-22 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_newuser_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='is_admin',
            new_name='is_active',
        ),
    ]
